language: go

go:
  - 1.13.x

git:
  depth: 1

install: skip

jobs:
  include:
    - stage: unit-test
      script:
        - go test -mod=vendor -v ./... -coverprofile ./coverage.txt
        - bash <(curl -s https://codecov.io/bash)

    - stage: publish-image
      if: type = push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export IMAGE=keikoproj/governor:$TRAVIS_BRANCH
        - make docker-build
        - make docker-push
